version: "3.3"

services:
    efrederick:
        container_name: portfolio_api_efrederick
        build:
            context: ./efrederick
            dockerfile: Dockerfile
        ports:
            - "9001:9001"           
        volumes:
            - ./efrederick/node_modules:/app/node_modules
        restart: unless-stopped            

    namah:
        container_name: portfolio_api_namah
        build:
            context: ./namah
            dockerfile: Dockerfile
        ports:
            - "9002:9002"                     
        volumes:
            - ./namah/node_modules:/app/node_modules
        restart: unless-stopped

    gifter:
        container_name: portfolio_api_gifter
        build:
            context: ./gifter
            dockerfile: Dockerfile
        ports:
            - "9003:9003"                     
        volumes:
            - ./gifter/node_modules:/app/node_modules
        restart: unless-stopped