version: "3.8"

services:
    projects:
        container_name: portfolio_web_api_projects
        build:
            context: ./services/web/projects
            dockerfile: Dockerfile
        ports:
            - "9001:9001"
        network_mode: "host"
        restart: unless-stopped

    namah:
        container_name: portfolio_web_api_namah
        build:
            context: ./services/web/namah
            dockerfile: Dockerfile
        ports:
            - "9002:9002"   
        network_mode: "host"           
        volumes:
            - /node_modules:/app/node_modules
        restart: unless-stopped

    gifter:
        container_name: portfolio_web_api_gifter
        build:
            context: ./services/web/gifter
            dockerfile: Dockerfile
        ports:
            - "9003:9003"
        network_mode: "host"
        volumes:
            - ./node_modules:/app/node_modules
        restart: unless-stopped

    dashboard:
        container_name: portfolio_web_api_dashboard
        build:
            context: ./services/web/dashboard
            dockerfile: Dockerfile
        ports:
            - "9004:9004"
        network_mode: "host"
        volumes:
            - ./node_modules:/app/node_modules
        restart: unless-stopped

    cors-anywhere:
        container_name: portfolio_web_api_cors-anywhere
        build:
           context: ./services/web/cors-anywhere
           dockerfile: Dockerfile
        ports:
            - "9005:9005"
        network_mode: "host"
        volumes:
             - ./node_modules:/app/node_modules
        restart: unless-stopped

    kirakirayaki:
        container_name: portfolio_web_api_kirakirayaki
        build:
           context: ./services/web/kirakirayaki
           dockerfile: Dockerfile
        ports:
            - "9006:9006"
        network_mode: "host"
        volumes:
             - ./node_modules:/app/node_modules
        restart: unless-stopped